server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_security_app
    username: postgres
    password: vishal
    driver-class-name: org.postgresql.Driver

#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 30000        # 30 seconds
#      connection-timeout: 30000  # 30 seconds
#      max-lifetime: 1800000      # 30 minutes
#      auto-commit: true
#      validation-timeout: 5000
#      leak-detection-threshold: 20000
#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
