server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_security_app
    username: postgres
    password: vishal
    driver-class-name: org.postgresql.Driver

#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 30000        # 30 seconds
#      connection-timeout: 30000  # 30 seconds
#      max-lifetime: 1800000      # 30 minutes
#      auto-commit: true
#      validation-timeout: 5000
#      leak-detection-threshold: 20000
#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET:jFfVhbW59aCk5pDhopplngKGwK646tHWwsDG9OMQW86MIvRzOLokdSTutVk5VpiUBrywbWjH1xKx0fG2CT3Hg5}
    issuer: ${JWT_ISSUER:app.authsecure.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}

